'use strict';

// tests for createItem
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('createItem', '/functions/items/create.item.js', 'createItemHandler');

describe('createItem', () => {
  before((done) => {
    done();
  });

  it('Create Item with no param body', () => {
    return wrapped.run({}).then((response) => {
      var createItemResponse = JSON.stringify(response);
      console.log(response.body.message);
      expect(createItemResponse).to.not.be.empty;
    });
  });
});
